### ISSUE TITLE
Problem In Qlikview Calendar

### ISSUE THREAD

**Issue by gnanasekar6914** [stefanwalther/qvD3CalendarView#4]
Hi, I'm new to QlikView and I have this problem, when I open my document locally I can use the calendar object to select multiple dates without problem, but just when I upload the same file to the [QlikView Software](https://mindmajix.com/qlikview-training) Server and acces it trhough the acces point, the calendar object looks different and doesn`t let me to choose a range of date values, only a single one.

**Opening Locally:**
![image](https://user-images.githubusercontent.com/30929392/33428315-51318b80-d5ee-11e7-963c-a044fb332c9a.png)

**After uploading it to the server:**
![image](https://user-images.githubusercontent.com/30929392/33428332-67fd1708-d5ee-11e7-98f1-3867401c502f.png)

Thank you for your time!
Gnanasekar

**Comment by stefanwalther** [comment]
I am very sorry to say, but you are asking a question related to the standard calendar control of QlikView, not to this extension. I recommend that you ask your question in QlikCommunity.
